kind: Deployment
apiVersion: apps/v1
metadata:
  name: 2048-game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-game-pod
  template:
    metadata:
      labels:
        app: 2048-game-pod
    spec:
      containers:
        - name: 2048-game-container
          image: bttger/2048-game:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 50M
